services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    ports:
      - "2222:2222"
    volumes:
      - ../cowrie.log:/cowrie/cowrie-git/cowrie.log
      - ../downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads
      - ./cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      # Final correct mount path for authentication database:
      - ./userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
    restart: always
